image: node:latest

cache:
  paths:
    - client/node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd client
    - npm ci
    # Spécifier explicitement la configuration production et le baseHref
    - npm run build -- --configuration production --base-href=/mspr-billeterie/
  artifacts:
    paths:
      - client/dist/MSPR/browser

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mkdir -p public
    - cp -r client/dist/MSPR/browser/* public/
    - cp client/dist/MSPR/browser/index.html public/404.html
    - touch public/.nojekyll
  artifacts:
    paths:
      - public
  only:
    - develop