# ====================
# SCALARS
# ====================
scalar LocalDateTime

# ====================
# TYPES
# ====================
type Artiste {
    id: Int!
    nom: String!
    urlArtistImage: String
    urlSocialMedia: String
    biographieComplete: String
}

type Scene {
    id: Int!
    name: String!
}

type Evenement {
    eventId: Int!
    eventName: String
    startTime: LocalDateTime!
    endTime: LocalDateTime!
    description: String!
    longDescription: String!
    categorie: CategorieEvenement!
    artiste: Artiste!
    scene: Scene!
}

enum CategorieEvenement {
    CONCERT
    DJ_SET
    ATELIER
    ANIMATION
    SHOPPING
    RENCONTRE
    FOOD
    CEREMONIE
}

# ====================
# INPUTS
# ====================
input ArtisteInput {
    nom: String!
    urlArtistImage: String
    urlSocialMedia: String
    biographieComplete: String
}

input SceneInput {
    name: String!
}

input EvenementInput {
    eventName: String!
    startTime: LocalDateTime!
    endTime: LocalDateTime!
    description: String
    longDescription: String
    categorie: CategorieEvenement!
    artisteId: Int!
    sceneId: Int!
}

# ====================
# QUERIES
# ====================
type Query {
    # Evenements
    getAllEvent: [Evenement!]!
}

# ====================
# MUTATIONS
# ====================