server:
  port: ${PORT:8080}

spring:
  graphql:
    graphiql:
      enabled: true
      base-path: /graphiql
    http:
      path: /graphql
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://127.0.0.1:5432/mspr-billeterie}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    default-schema: public
  liquibase:
    enabled: true
    change-log: classpath:db/changeLog/changelog-master.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

app:
  jwt:
    secret: ${JWT_SECRET:dW5lLWNsZWYtc2VjcmV0ZS1kZS0yNTYtYml0cy1taW5pbXVtLXBvdXItaHMyNTY=}
    expiration: 86400000 # 24h en ms
